Send an email when the tests fail

diff --git a/e2e-test/Jenkinsfile_Demo_Projects b/e2e-test/Jenkinsfile_Demo_Projects
--- a/e2e-test/Jenkinsfile_Demo_Projects
+++ b/e2e-test/Jenkinsfile_Demo_Projects
@@ -15,48 +15,57 @@ def elastest_network = env.NETWORK
 //inside the elastest_lib.pipeline({...})
 elastest_lib.pipeline({
     
-    stage ('docker container')
-        def mycontainer = elastest.ctx.docker.image('elastest/ci-docker-e2e:latest')
-        mycontainer.pull()
-        mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw -v /dev/shm:/dev/shm")  {
-            sh '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf &'
-            def testRepositoryDirectory = 'elastest'
-                  
-            stage ('prepare test')
-                def testDirectoryExists = fileExists 'elastest'
-                if (testDirectoryExists) {
-                    echo 'The elastest directory exists'
-                } else {
-                    echo 'There is no elastset directory'
-                    sh 'mkdir elastest'
-                }
+    try {
+        stage ('docker container')
+            def mycontainer = elastest.ctx.docker.image('elastest/ci-docker-e2e:latest')
+            mycontainer.pull()
+            mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw -v /dev/shm:/dev/shm")  {
+                sh '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf &'
+                def testRepositoryDirectory = 'elastest'
+                    
+                stage ('prepare test')
+                    def testDirectoryExists = fileExists 'elastest'
+                    if (testDirectoryExists) {
+                        echo 'The elastest directory exists'
+                    } else {
+                        echo 'There is no elastset directory'
+                        sh 'mkdir elastest'
+                    }
+                    
+                    dir(testRepositoryDirectory) {
+                        echo 'Existing files before cloning the git repository'
+                        git 'https://github.com/elastest/elastest-torm.git'
+                    }
                 
-                dir(testRepositoryDirectory) {
-                	echo 'Existing files before cloning the git repository'
-                    git 'https://github.com/elastest/elastest-torm.git'
-                }
-             
-                echo 'Prepare network'
-                elastest.connect2ElastestNetwork()
-                def elastestURL = elastest.getEtmUrl()
-                
-                stage ("DemoProjects E2E test")
-                	try {
-	                    echo "Run tests"
-	                    sh "cd elastest/e2e-test; mvn -B clean test -Dtest=io.elastest.etm.test.e2e.demoprojects.** -DetEtmApi=" + elastest.getEtmUrl() + " -DeUser=" + elastest.getElasTestUser() + " -DePass=" + elastest.getElasTestPassword() + " -DciUrl=" + ciUrl + " -Dsel.jup.recording=true -Dsel.jup.screenshot.at.the.end.of.tests=true -Dsel.jup.screenshot.format=png -Dsel.jup.output.folder=surefire-reports -Dsel.jup.docker.network="+elastest_network
-	                } catch(e) {
-                        echo 'Err: ' + e.toString()
-	                    sh '''\
-	                       docker ps --all
-	                       docker ps --filter name=etm -q
-	                       docker ps --filter name=etm -q | xargs -L 1 docker logs || true
-	                       docker ps --filter name=etm -q | xargs -L 1 docker inspect || true
-	                    '''
-	                } finally {
-	                    step([$class: 'JUnitResultArchiver', testDataPublishers: [[$class: 'AttachmentPublisher']], testResults: '**/target/surefire-reports/TEST-*.xml'])
-	                }
-        }
-  })
+                    echo 'Prepare network'
+                    elastest.connect2ElastestNetwork()
+                    def elastestURL = elastest.getEtmUrl()
+                    
+                    stage ("DemoProjects E2E test")
+                        try {
+                            echo "Run tests"
+                            sh "cd elastest/e2e-test; mvn -B clean test -Dtest=io.elastest.etm.test.e2e.demoprojects.** -DetEtmApi=" + elastest.getEtmUrl() + " -DeUser=" + elastest.getElasTestUser() + " -DePass=" + elastest.getElasTestPassword() + " -DciUrl=" + ciUrl + " -Dsel.jup.recording=true -Dsel.jup.screenshot.at.the.end.of.tests=true -Dsel.jup.screenshot.format=png -Dsel.jup.output.folder=surefire-reports -Dsel.jup.docker.network="+elastest_network
+                        } catch(e) {
+                            echo 'Err: ' + e.toString()
+                            sh '''\
+                            docker ps --all
+                            docker ps --filter name=etm -q
+                            docker ps --filter name=etm -q | xargs -L 1 docker logs || true
+                            docker ps --filter name=etm -q | xargs -L 1 docker inspect || true
+                            '''
+                            throw e
+                        } finally {
+                            step([$class: 'JUnitResultArchiver', testDataPublishers: [[$class: 'AttachmentPublisher']], testResults: '**/target/surefire-reports/TEST-*.xml'])
+                        }
+            }
+    } catch (err) {
+        echo 'Error!!! Send email to the people responsible for the builds.'
+        emailext body: "${BUILD_URL}",
+        replyTo: '${BUILD_USER_EMAIL}', 
+        subject: 'Job ${JOB_NAME} - ${BUILD_NUMBER} RESULT: ${BUILD_STATUS}', 
+        to: 'Please go to ${MAIL_LIST}  and verify the build'
+    }
+})
   
   def containerIp(containerName, network) {
     echo "Inside containerIp function"
diff --git a/e2e-test/Jenkinsfile_FullteachingTL b/e2e-test/Jenkinsfile_FullteachingTL
--- a/e2e-test/Jenkinsfile_FullteachingTL
+++ b/e2e-test/Jenkinsfile_FullteachingTL
@@ -12,62 +12,72 @@ def elastest= elastest_lib.getElastestMethods()
 //inside the elastest_lib.pipeline({...})
 elastest_lib.pipeline({
     
-    stage ('docker container')
-        def mycontainer = elastest.ctx.docker.image('elastest/ci-docker-e2e-compose:latest')
-        mycontainer.pull()
-        mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw -v /dev/shm:/dev/shm")  {
-            sh '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf &'
-            def testRepositoryDirectory = 'elastest'
-                  
-            stage ('prepare test')
-                def testDirectoryExists = fileExists 'elastest'
-                if (testDirectoryExists) {
-                    echo 'The elastest directory exists'
-                } else {
-                    echo 'There is no elastset directory'
-                    sh 'mkdir elastest'
-                }
+    try {
+
+        stage ('docker container')
+            def mycontainer = elastest.ctx.docker.image('elastest/ci-docker-e2e-compose:latest')
+            mycontainer.pull()
+            mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw -v /dev/shm:/dev/shm")  {
+                sh '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf &'
+                def testRepositoryDirectory = 'elastest'
+                    
+                stage ('prepare test')
+                    def testDirectoryExists = fileExists 'elastest'
+                    if (testDirectoryExists) {
+                        echo 'The elastest directory exists'
+                    } else {
+                        echo 'There is no elastset directory'
+                        sh 'mkdir elastest'
+                    }
+                    
+                    dir(testRepositoryDirectory) {
+                        echo 'Existing files before cloning the git repository'
+                        git 'https://github.com/elastest/elastest-torm.git'
+                    }
                 
-                dir(testRepositoryDirectory) {
-                	echo 'Existing files before cloning the git repository'
-                    git 'https://github.com/elastest/elastest-torm.git'
-                }
-             
-                echo 'Prepare network'
-                elastest.connect2ElastestNetwork()
-                def elastestURL = elastest.getEtmUrl()
-                
-            stage ("TestLink Fullteaching test")
-                try {
-				    echo "Start Fullteaching"
-				    sh "cd elastest/e2e-test; docker-compose -f src/test/resources/fullteaching.yml -p elastest up -d"
-				    echo "Wait for fullteaching started"
-				    sh "sleep 20"
+                    echo 'Prepare network'
+                    elastest.connect2ElastestNetwork()
+                    def elastestURL = elastest.getEtmUrl()
+                    
+                stage ("TestLink Fullteaching test")
+                    try {
+                        echo "Start Fullteaching"
+                        sh "cd elastest/e2e-test; docker-compose -f src/test/resources/fullteaching.yml -p elastest up -d"
+                        echo "Wait for fullteaching started"
+                        sh "sleep 20"
 
-                    def fullteachingIp = containerIp("elastest_full-teaching_1")
-                    echo "Fullteaching IP: " + fullteachingIp  
+                        def fullteachingIp = containerIp("elastest_full-teaching_1")
+                        echo "Fullteaching IP: " + fullteachingIp  
 
 
-                    echo "Run EtmTestLinkFullteachingE2eTest"
-                    sh "cd elastest/e2e-test; mvn -B clean test -Dtest=EtmTestLinkFullteachingE2eTest -DfullteachingIp="+ fullteachingIp +" -DfullteachingPort=5000 -DetEtmApi=http://172.17.0.1:37000 -Dsel.jup.recording=true -Dsel.jup.screenshot.at.the.end.of.tests=true -Dsel.jup.screenshot.format=png -Dsel.jup.output.folder=surefire-reports -Dsel.jup.docker.network=elastest_elastest"
-                } catch(e) {
-                    echo 'Err: ' + e.toString()
-                    sh '''\
-                       docker ps --all
-                       docker ps --filter name=etm -q
-                       docker ps --filter name=etm -q | xargs -L 1 docker logs || true
-                       docker ps --filter name=etm -q | xargs -L 1 docker inspect || true
-                    '''
-                } finally {
-                    try{
-				    	sh "cd elastest/e2e-test; docker-compose -f src/test/resources/fullteaching.yml -p elastest down"
-					} catch(e) {
-					    echo 'Error on stop Fullteaching docker compose: ' + e.toString()
-					}    
-                    step([$class: 'JUnitResultArchiver', testDataPublishers: [[$class: 'AttachmentPublisher']], testResults: '**/target/surefire-reports/TEST-*.xml'])
-                }
-        }
-  })
+                        echo "Run EtmTestLinkFullteachingE2eTest"
+                        sh "cd elastest/e2e-test; mvn -B clean test -Dtest=EtmTestLinkFullteachingE2eTest -DfullteachingIp="+ fullteachingIp +" -DfullteachingPort=5000 -DetEtmApi=http://172.17.0.1:37000 -Dsel.jup.recording=true -Dsel.jup.screenshot.at.the.end.of.tests=true -Dsel.jup.screenshot.format=png -Dsel.jup.output.folder=surefire-reports -Dsel.jup.docker.network=elastest_elastest"
+                    } catch(e) {
+                        echo 'Err: ' + e.toString()
+                        sh '''\
+                        docker ps --all
+                        docker ps --filter name=etm -q
+                        docker ps --filter name=etm -q | xargs -L 1 docker logs || true
+                        docker ps --filter name=etm -q | xargs -L 1 docker inspect || true
+                        '''
+                        throw e
+                    } finally {
+                        try{
+                            sh "cd elastest/e2e-test; docker-compose -f src/test/resources/fullteaching.yml -p elastest down"
+                        } catch(e) {
+                            echo 'Error on stop Fullteaching docker compose: ' + e.toString()
+                        }    
+                        step([$class: 'JUnitResultArchiver', testDataPublishers: [[$class: 'AttachmentPublisher']], testResults: '**/target/surefire-reports/TEST-*.xml'])
+                    }
+            }
+    } catch (err) {
+        echo 'Error!!! Send email to the people responsible for the builds.'
+        emailext body: "${BUILD_URL}",
+        replyTo: '${BUILD_USER_EMAIL}', 
+        subject: 'Job ${JOB_NAME} - ${BUILD_NUMBER} RESULT: ${BUILD_STATUS}', 
+        to: 'Please go to ${MAIL_LIST}  and verify the build'
+    }
+})
   
   def containerIp(containerName) {
     echo "Inside containerIp function"
diff --git a/e2e-test/Jenkinsfile_Plugin b/e2e-test/Jenkinsfile_Plugin
--- a/e2e-test/Jenkinsfile_Plugin
+++ b/e2e-test/Jenkinsfile_Plugin
@@ -16,80 +16,88 @@ def elastest_network = env.NETWORK
 //definition of nodes is managed by the library. Just declare the steps of your pipeline
 //inside the elastest_lib.pipeline({...})
 elastest_lib.pipeline({
-    
-    stage ('docker container')
-        def mycontainer = elastest.ctx.docker.image('elastest/ci-docker-e2e:latest')
-        mycontainer.pull()
-        mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw -v /dev/shm:/dev/shm")  {
-            sh '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf &'
-            def pluginPath = '/home/ubuntu/workspace/elastest-torm/etm-e2e-test-plugin/elastest-plugin/target/elastest.hpi'
-            def pluginDirectory = 'elastest-plugin'
-            def testRepositoryDirectory = 'elastest'
-          
-            stage('build ElasTest plugin')
-            	def pluginDirectoryExists = fileExists 'elastest-plugin'
-                if (pluginDirectoryExists) {
-                    echo 'The elastset-plugin exists'
-                } else {
-                    echo 'There is no elastset-plugin directory'
-                    sh 'mkdir elastest-plugin'
-                }
-            	dir(pluginDirectory) {
-            	    git 'https://github.com/elastest/elastest-jenkins.git'
-            	    echo 'Build ElasTest plugin'
-            	    sh 'cd elastest-plugin; pwd; ls -lrt; mvn clean package -B'
-            	}
+    try {    
+        stage ('docker container')
+            def mycontainer = elastest.ctx.docker.image('elastest/ci-docker-e2e:latest')
+            mycontainer.pull()
+            mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw -v /dev/shm:/dev/shm")  {
+                sh '/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf &'
+                def pluginPath = '/home/ubuntu/workspace/elastest-torm/etm-e2e-test-plugin/elastest-plugin/target/elastest.hpi'
+                def pluginDirectory = 'elastest-plugin'
+                def testRepositoryDirectory = 'elastest'
             
-            stage ('prepare test')
-                def testDirectoryExists = fileExists 'elastest'
-                if (pluginDirectoryExists) {
-                    echo 'The elastest directory exists'
-                } else {
-                    echo 'There is no elastset directory'
-                    sh 'mkdir elastest'
-                }
+                stage('build ElasTest plugin')
+                    def pluginDirectoryExists = fileExists 'elastest-plugin'
+                    if (pluginDirectoryExists) {
+                        echo 'The elastset-plugin exists'
+                    } else {
+                        echo 'There is no elastset-plugin directory'
+                        sh 'mkdir elastest-plugin'
+                    }
+                    dir(pluginDirectory) {
+                        git 'https://github.com/elastest/elastest-jenkins.git'
+                        echo 'Build ElasTest plugin'
+                        sh 'cd elastest-plugin; pwd; ls -lrt; mvn clean package -B'
+                    }
                 
-                dir(testRepositoryDirectory) {
-                	echo 'Existing files before cloning the git repository'
-                    git 'https://github.com/elastest/elastest-torm.git'
-                }
-             
-                echo 'Prepare network'
-                elastest.connect2ElastestNetwork()
-                def elastestURL = elastest.getEtmUrl()
+                stage ('prepare test')
+                    def testDirectoryExists = fileExists 'elastest'
+                    if (pluginDirectoryExists) {
+                        echo 'The elastest directory exists'
+                    } else {
+                        echo 'There is no elastset directory'
+                        sh 'mkdir elastest'
+                    }
+                    
+                    dir(testRepositoryDirectory) {
+                        echo 'Existing files before cloning the git repository'
+                        git 'https://github.com/elastest/elastest-torm.git'
+                    }
                 
-                echo 'Prepare Jenkins'
-                def etCustmizedJenkinsImage = elastest.ctx.docker.image('elastest/etm-jenkins:latest')
-                echo 'Object for the Jenkins image declared'
-                try {
-                    echo "Try to remove elastest_etm-jenkins_1 container if is started"
-        	        sh 'docker rm -f elastest_etm-jenkins_1'
-                } catch(e) {
-                    echo "elastest_etm-jenkins_1 container not started"
-                }
-                
-                etCustmizedJenkinsImage.withRun('--name elastest_etm-jenkins_1 -u 0 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" --network='+elastest_network) { c1 ->
-                    stage ("E2E tests")
-                    	
-                    	    echo "Jenkins Url: " + jenkinsUrl
-                    		echo "${c1.id}"                        
-                            def ciUrl = "http://" + containerIp(c1.id, elastest_network) + ":8080"
-                            echo "Jenkins URL: " + ciUrl                    
+                    echo 'Prepare network'
+                    elastest.connect2ElastestNetwork()
+                    def elastestURL = elastest.getEtmUrl()
+                    
+                    echo 'Prepare Jenkins'
+                    def etCustmizedJenkinsImage = elastest.ctx.docker.image('elastest/etm-jenkins:latest')
+                    echo 'Object for the Jenkins image declared'
+                    try {
+                        echo "Try to remove elastest_etm-jenkins_1 container if is started"
+                        sh 'docker rm -f elastest_etm-jenkins_1'
+                    } catch(e) {
+                        echo "elastest_etm-jenkins_1 container not started"
+                    }
+                    
+                    etCustmizedJenkinsImage.withRun('--name elastest_etm-jenkins_1 -u 0 --env JAVA_OPTS="-Djenkins.install.runSetupWizard=false" --network='+elastest_network) { c1 ->
+                        stage ("E2E tests")
                             
-        	                try {
-        	                    echo "Run tests"
-        	                    sh "cd elastest/e2e-test; mvn -B clean test -Dtest=io.elastest.etm.test.e2e.plugin.** -DePluginPath=" + pluginPath + " -DetEtmApi=" + elastest.getEtmUrl() + " -DeUser=" + elastest.getElasTestUser() + " -DePass=" + elastest.getElasTestPassword() + " -DciUrl=" + ciUrl + " -Dsel.jup.recording=true -Dsel.jup.screenshot.at.the.end.of.tests=true -Dsel.jup.screenshot.format=png -Dsel.jup.output.folder=surefire-reports -Dsel.jup.docker.network="+elastest_network
-        	                } catch(e) {
-        	                    sh '''\
-        	                       docker ps --all
-        	                       docker ps --filter name=etm -q
-        	                       docker ps --filter name=etm -q | xargs -L 1 docker logs || true
-        	                       docker ps --filter name=etm -q | xargs -L 1 docker inspect || true
-        	                    '''
-        	                } finally {
-        	                    step([$class: 'JUnitResultArchiver', testDataPublishers: [[$class: 'AttachmentPublisher']], testResults: '**/target/surefire-reports/TEST-*.xml'])
-        	                }
-    	            }
+                                echo "Jenkins Url: " + jenkinsUrl
+                                echo "${c1.id}"                        
+                                def ciUrl = "http://" + containerIp(c1.id, elastest_network) + ":8080"
+                                echo "Jenkins URL: " + ciUrl                    
+                                
+                                try {
+                                    echo "Run tests"
+                                    sh "cd elastest/e2e-test; mvn -B clean test -Dtest=io.elastest.etm.test.e2e.plugin.** -DePluginPath=" + pluginPath + " -DetEtmApi=" + elastest.getEtmUrl() + " -DeUser=" + elastest.getElasTestUser() + " -DePass=" + elastest.getElasTestPassword() + " -DciUrl=" + ciUrl + " -Dsel.jup.recording=true -Dsel.jup.screenshot.at.the.end.of.tests=true -Dsel.jup.screenshot.format=png -Dsel.jup.output.folder=surefire-reports -Dsel.jup.docker.network="+elastest_network
+                                } catch(e) {
+                                    sh '''\
+                                    docker ps --all
+                                    docker ps --filter name=etm -q
+                                    docker ps --filter name=etm -q | xargs -L 1 docker logs || true
+                                    docker ps --filter name=etm -q | xargs -L 1 docker inspect || true                                    
+                                    '''
+                                    throw e
+                                } finally {
+                                    step([$class: 'JUnitResultArchiver', testDataPublishers: [[$class: 'AttachmentPublisher']], testResults: '**/target/surefire-reports/TEST-*.xml'])
+                                }
+                        }
+            }
+        } catch (err) {
+            echo 'Error!!! Send email to the people responsible for the builds.'
+            emailext body: "${BUILD_URL}",
+            replyTo: '${BUILD_USER_EMAIL}', 
+            subject: 'Job ${JOB_NAME} - ${BUILD_NUMBER} RESULT: ${BUILD_STATUS}', 
+            to: 'Please go to ${MAIL_LIST}  and verify the build'
         }
   })
   
